### ISSUE TITLE
Rename index to products 

### ISSUE THREAD

**Issue by mathiasfk** [codingexplained/complete-guide-to-elasticsearch#15]
In some old videos, you still using the index named as `product` instead of `products`. As the video that shows the creation of the index uses the name `products`, I think it make sense to use this same name in all examples.

**Comment by mathiasfk** [comment]
https://github.com/codingexplained/complete-guide-to-elasticsearch/pull/14

**Comment by ba0708** [comment]
Merged. Was going to fix it soon as I am working on remaking those sections, but might as well do it now. Thanks, @mathiasfk! 🙂
