### ISSUE TITLE
Wrong Link to importing-data-with-curl.md 

### ISSUE THREAD

**Issue by ZaidAfane3** [codingexplained/complete-guide-to-elasticsearch#23]
Hello, 
in [querying-nested-objects.md](https://github.com/codingexplained/complete-guide-to-elasticsearch/blob/ee839b93f906d85ea35ca74cd09aa057d5b0eb43/Searching%20for%20Data/querying-nested-objects.md), the "**Follow Instruction**" link is wrong and gives a 404 page.

**Comment by ba0708** [comment]
Fixed in https://github.com/codingexplained/complete-guide-to-elasticsearch/commit/0020cc704d664c30b00a0e003d5722a0be542740

Thank you for finding and reporting this issue, @ZaidAfane3! 🙂
