### ISSUE TITLE
Bulk Import - erroring in Power shell and Git Bash shell

### ISSUE THREAD

**Issue by cetmca** [codingexplained/complete-guide-to-elasticsearch#27]
hi Bo,

while importing the products.json file, i am getting this below error in Power shell..

curl  -H "Content-Type: application/x-ndjson" -XPOST http://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"

PS C:\ms\complete-guide-to-elasticsearch> curl  -H "Content-Type: application/x-ndjson" -XPOST http://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"
Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Content-Type: application/x-ndjson" value of type "System.String" to type "System.Collections.IDictionary".
At line:1 char:10
+ curl  -H "Content-Type: application/x-ndjson" -XPOST http://localhost ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    
    
    
    But in Git Bash : I am getting the below response. not been able to import to ES.
    
    
    anila@DESKTOP-GFR2COL MINGW64 /c/ms/complete-guide-to-elasticsearch (master)
$ curl  -H "Content-Type: application/x-ndjson" -XPOST http://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  354k    0     0  100  354k      0  47.9M --:--:-- --:--:-- --:--:-- 49.3M
curl: (52) Empty reply from server

**Comment by ba0708** [comment]
Hi @cetmca,

Please ask questions within the course Q&A 🙂 

Please try the following:
1. Remove the space within the header so it becomes `Content-Type:application/x-ndjson`. I have seen a space there cause issues on Windows before.
2. Unless you are using an old version of Elasticsearch, you should use `https://` instead of `http://` and also authenticate your request by adding `-u elastic` to your command.

If the above does not solve the issue, feel free to post within the course Q&A 🙂 

Best regards,
Bo Andersen

**Comment by cetmca** [comment]
tried the same, and it still fails, 
I have updated the question in the udemy course Q&A also.


Error I am getting, tried -u option as well

curl  -H "Content-Type:application/x-ndjson" -XPOST https://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"

PS C:\ms\complete-guide-to-elasticsearch> curl  -H "Content-Type:application/x-ndjson" -XPOST https://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"
Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Content-Type:application/x-ndjson" value of type "System.String" to type "System.Collections.IDictionary".
At line:1 char:10
+ curl  -H "Content-Type:application/x-ndjson" -XPOST https://localhost ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\ms\complete-guide-to-elasticsearch>



PS C:\ms\complete-guide-to-elasticsearch> curl  -H -u elastic "Content-Type:application/x-ndjson" -XPOST https://localhost:9200/products/_bulk  --data-binary "@products-bulk.json"


Invoke-WebRequest : Parameter cannot be processed because the parameter name 'u' is ambiguous. Possible matches include: -UseBasicParsing -Uri -UseDefaultCredentials -UserAgent.
At line:1 char:10
+ curl  -H -u elastic "Content-Type:application/x-ndjson" -XPOST https: ...
+          ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
