### ISSUE TITLE
Want to search list of parents having both words in the list of childs

### ISSUE THREAD

**Issue by pkmbackdev** [codingexplained/complete-guide-to-elasticsearch#3]
I want to search restaurant having both "burger" and "chicken" exist in there menus. Can you please provide me ES query for that
```
-Restaurant1
      -menu1
          -pizza
          -burger
      -menu2
          -rice
          -chicken
-Restaurant2
      -menu1
          -pizza
          -lobster
      -menu2
          -chicken
          -lamb
```

**Comment by ba0708** [comment]
Hello @bittu1984. Please use for course Q&A for questions. Also, I do not write queries for people, but I do answer questions and give pointers and advice whenever I can. :-)
